const company_list =  [
  {
	image: '/static/google.png',
	title: '谷歌Google',
	//subtitle: 'Software Engineer',
	tag: '全职',
	views: 2344,
	file: '/backend/pdfs/google.pdf',
  },
  {
	image: '/static/tiktok.png',
	title: 'Microsoft微软',
	//subtitle: 'Senior Data Scientist',
	tag: '实习',
	views: 3452,
	file: '/backend/pdfs/tiktok.pdf',
  },
  {
	image: '/static/meta.png',
	title: 'Alibaba阿里巴巴',
	//subtitle: 'Software Engineer',
	tag: '实习',
	views: 4697,
	file: '/backend/pdfs/meta.pdf',
  },
  {
  	image: '/static/meta.png',
  	title: 'Tencent腾讯',
  	//subtitle: 'Software Engineer',
  	tag: '实习',
  	views: 4697,
  	file: '/backend/pdfs/meta.pdf',
  },
  {
  	image: '/static/meta.png',
  	title: 'Meta',
  	//subtitle: 'Software Engineer',
  	tag: '实习',
  	views: 4697,
  	file: '/backend/pdfs/meta.pdf',
  },
  {
  	image: '/static/meta.png',
  	title: 'Meta',
  	//subtitle: 'Software Engineer',
  	tag: '实习',
  	views: 4697,
  	file: '/backend/pdfs/meta.pdf',
  },
  {
  	image: '/static/meta.png',
  	title: 'Meta',
  	//subtitle: 'Software Engineer',
  	tag: '实习',
  	views: 4697,
  	file: '/backend/pdfs/meta.pdf',
  },
  {
  	image: '/static/google.png',
  	title: '谷歌Google',
  	//subtitle: 'Software Engineer',
  	tag: '全职',
  	views: 2344,
	file: '/backend/pdfs/google.pdf',
  },
  // Add more items as needed
];
const university_list =  [
  {
	image: '/static/nyu.png',
	title: '经济学',
	//subtitle: '经济学',
	// tag: '全职',
	views: 2344,
	file: '/backend/pdfs/nyu.pdf',
  },
  {
	image: '/static/toronto.png',
	title: '心理学',
	//subtitle: '心理学',
	// tag: '实习',
	views: 3452,
	file: '/backend/pdfs/toronto.pdf',
  },
  {
	image: '/static/columbia.png',
	title: '数学',
	//subtitle: '应用分析学',
	// tag: '实习',
	views: 4697,
	file: '/backend/pdfs/columbia.pdf',
  },
  {
  	image: '/static/nyu.png',
  	title: '数据科学',
  	//subtitle: '经济学',
  	// tag: '全职',
  	views: 2344,
	file: '/backend/pdfs/nyu.pdf',
  },
  {
  	image: '/static/toronto.png',
  	title: '计算机科学',
  	//subtitle: '心理学',
  	// tag: '实习',
  	views: 3452,
	file: '/backend/pdfs/toronto.pdf',
  },
  {
  	image: '/static/columbia.png',
  	title: '应用分析学',
  	//subtitle: '应用分析学',
  	// tag: '实习',
  	views: 4697,
	file: '/backend/pdfs/columbia.pdf',
  },
  // Add more items as needed
];

export { company_list, university_list };
